### ISSUE TITLE
i can't scan achivement 'nobody knows slumbernana better than me"

### ISSUE THREAD

**Issue by DariaMinakina** [hashblen/HSRAchievementScanner#5]
when the scanner reaches this point, it issues an error, as I understand it, due to the fact that there have been no updates to the scanner database for a long time.

**Comment by hashblen** [comment]
You are right, I didn't update it for months now and deprecated the project, as I developed a better solution to instantly get the achievements without unreliable OCR scanning. You can find it at https://github.com/juliuskreutz/stardb-exporter if you are interested. If not, I can quickly update the database just this once but I won't guarantee the scanning will work well.

**Comment by DariaMinakina** [comment]
thanks for the link, it works great, so I don't need to update anymore.
